force-app/main/default/lwc-logger/objects/Logger_Setting__mdt/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Logger_Setting__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/lwc-logger/objects/Logger_Setting__mdt/fields/Usesr_Ids__c.field-meta.xml
<CustomField>
    <fullName>Usesr_Ids__c</fullName>
    <label>Usesr Ids</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LoggerSettingsController.cls
public with sharing class LoggerSettingsController {

  private final static string CMDT_NAME = 'Logger_Setting__mdt';


  @AuraEnabled
  public static string createCustomMetadataRecord(Map<String, String> fieldsMap){
    String deploymentId = '';
    try {
      Map<String, String> fieldValues = new Map<String, String>();

      fieldValues.put('Component_Name__c', fieldsMap.get('componentName'));
      fieldValues.put('Level__c', fieldsMap.get('level'));
      fieldValues.put('Usesr_Ids__c', fieldsMap.get('userIds'));

      ICustomMetadataManager metadataManager = new CustomMetadataManager();
      CustomMetadataService cmdtService = new CustomMetadataService(metadataManager);
      deploymentId = cmdtService.createCustomMetadataRecord(CMDT_NAME, fieldsMap.get('recordName'), fieldsMap.get('recordLabel'), fieldValues);
      //CustomMetadataService cmdtService = new CustomMetadataService(CMDT_NAME, fieldsMap.get('recordName'), fieldsMap.get('recordLabel'), fieldValues);
      //deploymentId = cmdtService.createCustomMetadataRecord();
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }

    return deploymentId;
  }
}