force-app/main/default/objects/Log__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <label>Current User</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Object_Ids__c.field-meta.xml
<CustomField>
    <fullName>Object_Ids__c</fullName>
    <label>Object Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/Log_Event__c.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <nameField>
        <label>Log Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Event__c/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Log_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log_Event__c/fields/Object_Ids__c.field-meta.xml
<CustomField>
    <fullName>Object_Ids__c</fullName>
    <label>Object Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/lwc-logger/classes/LoggingEventTriggerHandler.cls
public with sharing class LoggingEventTriggerHandler {

  public static void afterInsertHandler(List<Log__e> loggedPlatformEvents) {
    List<Log_Event__c> loggingRecordsToCreate = new List<Log_Event__c>();

    for(Log__e loggedPlatformEvent : loggedPlatformEvents) {
        Log_Event__c logRecord = new Log_Event__c();
        logRecord.Component_Name__c = loggedPlatformEvent.Component_Name__c;
        logRecord.Current_User__c = loggedPlatformEvent.CreatedById;
        logRecord.Level__c = loggedPlatformEvent.Level__c;
        logRecord.Message__c = loggedPlatformEvent.Message__c;
        logRecord.Object_Ids__c	 = loggedPlatformEvent.Object_Ids__c;
        logRecord.Stack_Trace__c = loggedPlatformEvent.Stack_Trace__c;

        loggingRecordsToCreate.add(logRecord);
     }

     insert loggingRecordsToCreate;
  }
}