force-app/main/default/objects/Logger_Setting__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/lwc-logger/objects/Logger_Setting__mdt/fields/Usesr_Ids__c.field-meta.xml
<CustomField>
    <fullName>Usesr_Ids__c</fullName>
    <label>Usesr Ids</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LoggingService.cls
public with sharing class LoggingService {

  private static Logger_Setting__mdt getLoggingMdtByName(String loggingComponentName) {
    return Logger_Setting__mdt.getInstance(loggingComponentName);
  }

  private static Boolean checkIfLoggingIsEnabled(Logger_Setting__mdt loggingMdt) {

    if (loggingMdt == null) {
      return null;
    }

    String userIdsEnabledForLogging = loggingMdt.Usesr_Ids__c.trim();
    Boolean isLoggingEnabledForUser = userIdsEnabledForLogging.equalsIgnoreCase('ALL') ||
        userIdsEnabledForLogging.containsIgnoreCase(String.valueOf(UserInfo.getUserId()).left(15));

    return isLoggingEnabledForUser;

  }

  private static String fetchLoggingLevel(Logger_Setting__mdt loggingMdt) {
    if (loggingMdt == null) {
      return '';
    }

    if (String.isNotBlank(loggingMdt.Level__c)) {
      return loggingMdt.Level__c;
    }

    return '';
  }

  @AuraEnabled
  public static Map<String, String> getLoggingMetadata(String componentName) {
    Map<String, String> loggingMap = new Map<String, String>();
    Logger_Setting__mdt loggingMdt = getLoggingMdtByName(componentName);

    System.debug('loggingMdt: '+loggingMdt);
    try {
      Boolean isLoggingEnabledForUser = checkIfLoggingIsEnabled(loggingMdt);
      loggingMap.put(
        'isLoggingEnabled',
        String.valueOf(isLoggingEnabledForUser)
      );

      String loggingLevel = fetchLoggingLevel(loggingMdt);
      loggingMap.put('loggingLevel', loggingLevel);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }

    System.debug('loggingMap: '+loggingMap);
    return loggingMap;
  }

  @AuraEnabled
  public static void createLoggingRecords(Map<String, String> fieldsMap) {
    Logger.getInstance().createLogs(fieldsMap);
  }
}